name: getx_initial_setup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_spinkit: ^5.0.0
  get: ^4.6.6
  dio: ^5.4.0
  cached_network_image: ^3.2.0
  retry: ^3.1.0
  get_storage: ^2.0.3
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  flutter_web_pagination: ^0.0.3
  numberpicker: ^2.1.2
  wheel_slider: ^1.1.1
  intl: ^0.17.0
  flutter_fancy_tree_view: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
